title: Blog Your PhD
author: kkelchte
email: klaas.kelchtermans~at~esat.kuleuven.be
description: > # this means to ignore newlines until "baseurl:"
  This place might become a blog place where I can put primal text of my phd.
  Or maybe an overview of new results.

github_username:  kkelchte

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
